spring:
  application:
    name: discovery-server

server:
  port: 8900

eureka:
  instance:
    hostname: discovery-server.default
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    preferIpAddress: true

logging:
  level:
    root: info
    com.shareimg: debug
    org.springframework: error
  path: .
