server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///var/lib/config-repo
      discovery:
        enabled: true
        serviceId: discovery-server
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:WuzrZJp4xsvGU@${spring.cloud.config.discovery.serviceId}.default:8900/eureka

logging:
  level:
    root: info
    com.shareimg: debug
    org.springframework: error
  path: .
